### ISSUE TITLE
adding filters to list?

### ISSUE THREAD

**Issue by andretx** [meanbee/magento-infinite-scroll#3]
How can I add filters to the list of results?
the code does not work
`$collection = Mage::getResourceModel('catalog/product_collection')
    ->addFieldToFilter('composition' => $composition);` 

https://github.com/meanbee/magento-infinite-scroll/blob/develop/app/code/community/Meanbee/InfiniteScroll/controllers/AjaxController.php

would have any tips?

**Comment by tgerulaitis** [comment]
Hi @andretx,

InfiniteScroll doesn't load the collection of products to be displayed itself, it just uses the regular catalog layout handles. So the product collection is loaded in the `Mage_Catalog_Model_Layer::getProductCollection` method, like in regular catalog pages.

You could override that method and add a filter to the collection there, but that's going to override it for normal catalog page loads and the Ajax InfiniteScroll loads. If you wanted to add the filter to the Ajax loads only, then you'll have to replace the layer block in the `infinitescroll_ajax_category` and `infinitescroll_ajax_search` layout handles.

Cheers,
Tomas

**Comment by andretx** [comment]
Hi, I've tried adding the filters to the infinitescroll_ajax_category and infinitescroll_ajax_search layout. unsuccessfully.

in
https://github.com/meanbee/magento-infinite-scroll/blob/4bca6e75f3dc24b917ab35f7debdabdb019066fa/app/code/community/Meanbee/InfiniteScroll/controllers/AjaxController.php#L3

I tried to change the function categoryAction ().
Would you have any more tips?

thanks in advance

**Comment by tgerulaitis** [comment]
@andretx , sorry, I can't think of any other ways. Category product collections get instantiated by the `Mage_Catalog_Model_Layer` class, which is normally only instantiated by the layout render. It is a singleton, though, so maybe you could do `Mage::getSingleton('catalog/layer')->getProductCollection()` in the controller and add your filters that way.
