### ISSUE TITLE
scroll not working after filter reset

### ISSUE THREAD

**Issue by dindy3000** [meanbee/magento-infinite-scroll#4]
Infinite scroll works fine, until you being incorporating filters and then it stops working, even when you clear all filter options. Only way to fix for the frontend user is for them to refresh the page, otherwise they are just left with the first 20 items.

**Comment by punkstar** [comment]
Hey @dindy3000. Could you flesh this issue out a bit please? Can we have:

* Expected behaviour
* Actual behaviour
* Steps to reproduce
* Magento Version
* PHP Version
