### ISSUE TITLE
Add Block after Button via XML

### ISSUE THREAD

**Issue by bytes-max** [meanbee/magento-infinite-scroll#5]
I want to add a static block after the Button without editing infinitescroll.xml or scripts.phtml, however, my custom code does not add it properly:

```
<?xml version="1.0"?>
<layout version="0.1.0">
    <catalog_category_default>
        <block type="contactform/form" as="contactform" after="meanbee.infinitescroll.script"/>
    </catalog_category_default>
</layout>
```
However, Mage seems not to find it. Any ideas?

**Comment by punkstar** [comment]
This isn't valid Magento layout XML. You need to put your block inside another block that's calling `$this->getChildHtml()`,
