### ISSUE TITLE
Infinity Scroll Not Working in One Category 

### ISSUE THREAD

**Issue by shihassulaiman** [meanbee/magento-infinite-scroll#7]

**Comment by shihassulaiman** [comment]
Hello. 

I have installed this infinity scroll module to  my Magento 1.9.4.0 store. This infinity scroll not working one category product list. Other categories working fine, 

Please check below url for category. 
https://www.beautymil.com/fragrances/44.html

also Check other categories.

Please check and let know what is the issue.  

Thanks in Advance
Shihas

**Comment by bobbyshaw** [comment]
Hi Shishas,

From what I can see, it's working on https://www.beautymil.com/fragrances/44.html as well, it's just that all products from that category are already being shown so there are no further pages to check. 

There are two ways that I checked this:

1. There are no links to the next page in the HTML source, like there are on other categories, e.g. https://www.beautymil.com/-1460.html does.
2. If you add ?limit=all to the URL, it doesn't show any more products, whereas https://www.beautymil.com/-1460.html does.

**Comment by shihassulaiman** [comment]
Hello 

PLease check below url . infinity scroll load more button working only two button click  in one category 

https://beautymil.corecodesoftwares.com/-1458.html

**Comment by bobbyshaw** [comment]
Your server doesn't respond with any content on the third page so I would recommend that you investigate server-side for any errors to identify what might be happening.
