### ISSUE TITLE
Infinity Scroll Not Working in One Category

### ISSUE THREAD

**Issue by shihassulaiman** [meanbee/magento-infinite-scroll#8]
Hello.

I have installed this infinity scroll module to my Magento 1.9.4.0 store. This infinity scroll not working one category product list. Other categories working fine,

PLease check below url . infinity scroll load more button working only two button click in one category

https://beautymil.corecodesoftwares.com/-1458.html

also Check other categories.

Please check and let know what is the issue.

Thanks in Advance
Shihas

**Comment by bobbyshaw** [comment]
Your server doesn't respond with any content on the third page so I would recommend that you investigate server-side for any errors to identify what might be happening.
