### ISSUE TITLE
Have to scroll to the bottom of the page before it will start loading the next page

### ISSUE THREAD

**Issue by ghost** [meanbee/magento-infinite-scroll#9]
Is there a value i can change to load the next page before getting to the bottom of the page? On mobile it looks like the last product is loaded and doesn't start loading the next page until you scroll all the way to the bottom past where most customers might stop.

**Comment by bobbyshaw** [comment]
Hi @colin121212, the scroll distance is currently hard-coded on this line https://github.com/meanbee/magento-infinite-scroll/blob/develop/app/code/community/Meanbee/InfiniteScroll/Block/Script.php#L59

Ideally this would be pulled out into a system.xml configuration value but you could instead rewrite this block to increaes the value. 

The other way of doing it would be to override the scroll distance as part of the js initialization (i.e. where this value is used): https://github.com/meanbee/magento-infinite-scroll/blob/develop/app/design/frontend/base/default/template/meanbee/infinitescroll/script.phtml#L21

**Comment by ghost** [comment]
Is this value in pixels from the bottom? I have tried changing it and it didn't make a difference.

**Comment by bobbyshaw** [comment]
Yes it is. Were you able to resolve this issue? Did you confirm that your change was reflected on the frontend when you viewed the source of the page?
